// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAThzV5wAYwze0hg6XuQ_t91YBPKbxRBVM',
    appId: '1:931817896570:web:9e50a661ada7080fd899c3',
    messagingSenderId: '931817896570',
    projectId: 'studentms-f1971',
    authDomain: 'studentms-f1971.firebaseapp.com',
    storageBucket: 'studentms-f1971.appspot.com',
    measurementId: 'G-9WV12ZKV3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw_M0RByboKLTU5OzmNGe6h3kVIRi0jIg',
    appId: '1:931817896570:android:2304f063bcb32e06d899c3',
    messagingSenderId: '931817896570',
    projectId: 'studentms-f1971',
    storageBucket: 'studentms-f1971.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_tnlFEtO5vBel7eBrrCqWAsabPh2XEqY',
    appId: '1:931817896570:ios:82df43f83e2ab286d899c3',
    messagingSenderId: '931817896570',
    projectId: 'studentms-f1971',
    storageBucket: 'studentms-f1971.appspot.com',
    iosBundleId: 'com.example.studentms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_tnlFEtO5vBel7eBrrCqWAsabPh2XEqY',
    appId: '1:931817896570:ios:82df43f83e2ab286d899c3',
    messagingSenderId: '931817896570',
    projectId: 'studentms-f1971',
    storageBucket: 'studentms-f1971.appspot.com',
    iosBundleId: 'com.example.studentms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAThzV5wAYwze0hg6XuQ_t91YBPKbxRBVM',
    appId: '1:931817896570:web:b832ecdee82038bed899c3',
    messagingSenderId: '931817896570',
    projectId: 'studentms-f1971',
    authDomain: 'studentms-f1971.firebaseapp.com',
    storageBucket: 'studentms-f1971.appspot.com',
    measurementId: 'G-F2J67GKN9Z',
  );
}
